<a href="https://colab.research.google.com/github/wantuds-crypto/Ciencia-datos-curso/blob/main/Final_precios_inmuebles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("debayank2024/house-price-prediction")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'house-price-prediction' dataset.
Path to dataset files: /kaggle/input/house-price-prediction

In [83]:
import os
import pandas as pd
df = pd.read_csv(os.path.join(path, "modified_data.csv"))
print("Filas y columnas:", df.shape)
df.info()
df.head()

Filas y columnas: (4600, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            4600 non-null   object
 1   price           4600 non-null   float64
 2   bedrooms        4600 non-null   float64
 3   bathrooms       4600 non-null   float64
 4   sqft_living     4600 non-null   int64
 5   sqft_lot        4600 non-null   int64
 6   floors          4600 non-null   float64
 7   waterfront      4600 non-null   int64
 8   view            4600 non-null   int64
 9   condition       4600 non-null   int64
 10  sqft_above      4600 non-null   int64
 11  sqft_basement   4600 non-null   int64
 12  yr_built        4600 non-null   int64
 13  yr_renovated    4600 non-null   int64
 14  street          4600 non-null   object
 15  city            4600 non-null   object
 16  statezip        4600 non-null   object
 17  price_per_sqft  4600 non-null   float64
dtypes: float64(5), int64(9), object(4)
memory usage: 647.0+ KB

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,price_per_sqft
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,233.58
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,653.15
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,177.20
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,210.00
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,283.51

In [84]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,price_per_sqft
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261,265.876209
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536,357.503362
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000,180.817500
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000,243.855000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000,314.840000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000,22533.900000

## 1. Formato Fechas
-pasar el date a formato fecha y además agregar una columna solo con el mes para determinar si hay meses que las viviendas son más costosas que otros.

In [85]:
df["date"] = pd.to_datetime(df["date"])
df = df.assign(
    mes=df['date'].dt.month
)

In [86]:
df2 = df.drop(columns=["street"])
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            4600 non-null   datetime64[ns]
 1   price           4600 non-null   float64
 2   bedrooms        4600 non-null   float64
 3   bathrooms       4600 non-null   float64
 4   sqft_living     4600 non-null   int64
 5   sqft_lot        4600 non-null   int64
 6   floors          4600 non-null   float64
 7   waterfront      4600 non-null   int64
 8   view            4600 non-null   int64
 9   condition       4600 non-null   int64
 10  sqft_above      4600 non-null   int64
 11  sqft_basement   4600 non-null   int64
 12  yr_built        4600 non-null   int64
 13  yr_renovated    4600 non-null   int64
 14  city            4600 non-null   object
 15  statezip        4600 non-null   object
 16  price_per_sqft  4600 non-null   float64
 17  mes             4600 non-null   int32
dtypes: datetime64[ns](1), float64(5), int32(1), int64(9), object(2)
memory usage: 629.0+ KB

In [87]:
df.select_dtypes(include=['bool']).info()
df.select_dtypes(include=['object']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Empty DataFrame
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   street    4600 non-null   object
 1   city      4600 non-null   object
 2   statezip  4600 non-null   object
dtypes: object(3)
memory usage: 107.9+ KB

Problematica: Predecir o explicar el precio de venta de una vivienda a partir de sus características físicas y de ubicación, para apoyar decisiones como fijar el precio de listado de una propiedad, detectar propiedades sub o sobrevaloradas en el mercado, o entender qué atributos son los que más elevan el valor de una casa

| No. | Problemática | Descripción | Columna(s) afectada(s) |
|---|---|---|---|
| 1 | Ubicación fragmentada | La ubicación está repartida en `street`, `city` y `statezip`, con demasiadas categorías únicas para usarlas directamente en un modelo; hay que decidir cómo resumirla (por ciudad, código postal o zona). | `street`, `city`, `statezip` |
| 2 | Variables redundantes / fuga de información | `sqft_above` + `sqft_basement` ≈ `sqft_living`, y `price_per_sqft` ya se calculó a partir de `price` y `sqft_living`; puede usarse para predecir `price` | `sqft_above`, `sqft_basement`, `sqft_living`, `price_per_sqft` |
| 3 | Valor centinela mal interpretado | `yr_renovated` = 0 no significa "año cero", sino "nunca renovacion"; tratarlo como año real distorsiona promedios y modelos. | `yr_renovated` |
| 4 | Escalas ordinales tratadas como numéricas | `condition` y `view` son categorías ordenadas, no cantidades continuas; hay que decidir si tratarlas como categóricas ordenadas o asumir distancia uniforme entre niveles. | `condition`, `view` |
| 5 | Desbalance de clases | `waterfront` probablemente tiene muy pocos casos en 1, lo que puede sesgar cualquier análisis o modelo que la use como variable importante. | `waterfront` |
| 6 | Estacionalidad / tendencia temporal | `date` permite ver si los precios varían por época del año, pero exige tratarla como serie de tiempo y no solo como etiqueta. | `date` |

## 2. Limpieza de datos

- Eliminamos duplicados exactos.
- Imputamos nulos (mediana para numéricas, moda para categóricas).
- Casteamos cada columna al tipo que le corresponde.
- Corregimos el valor centinela `yr_renovated == 0` (no es "año cero", es "nunca renovada").
- Hay Viviendas Precios =0.
-se eliminan estas columnas porque street cuenta con muchos datos unicos

### Preguntas y decisiones para el trabajo

- por que razon dejamos los datos nulos
- por que razon usamos la media
- por que razon eliminados 100 registros y asi

In [88]:
print("Nulos por columna:")
print(df.isnull().sum())

print("\nFilas duplicadas exactas:", df.duplicated().sum())

Nulos por columna:
date              0
price             0
bedrooms          0
bathrooms         0
sqft_living       0
sqft_lot          0
floors            0
waterfront        0
view              0
condition         0
sqft_above        0
sqft_basement     0
yr_built          0
yr_renovated      0
street            0
city              0
statezip          0
price_per_sqft    0
mes               0
dtype: int64

Filas duplicadas exactas: 0

In [89]:
##- No tenemos nulos ni duplicados, de igual forma se aplica la limpieza para una segunda validacion
import numpy as np

# Eliminar duplicados exactos
antes = df.shape[0]
df = df.drop_duplicates().reset_index(drop=True)
print(f"Duplicados eliminados: {antes - df.shape[0]}")

# Imputación de nulos
num_cols_check = df.select_dtypes(include=[np.number]).columns
cat_cols_check = df.select_dtypes(include=['object']).columns

for c in num_cols_check:
    if df[c].isnull().sum() > 0:
        df[c] = df[c].fillna(df[c].median())

for c in cat_cols_check:
    if df[c].isnull().sum() > 0:
        df[c] = df[c].fillna(df[c].mode()[0])

print("Nulos restantes:", df.isnull().sum().sum())

Duplicados eliminados: 0
Nulos restantes: 0

In [90]:
# Casteo de tipos
df['date'] = pd.to_datetime(df['date'])
df['waterfront'] = df['waterfront'].astype(bool)

for c in ['city', 'street', 'statezip']:
    df[c] = df[c].astype('category')

cat_condition = pd.CategoricalDtype(categories=sorted(df['condition'].unique()), ordered=True)
df['condition'] = df['condition'].astype(cat_condition)

cat_view = pd.CategoricalDtype(categories=sorted(df['view'].unique()), ordered=True)
df['view'] = df['view'].astype(cat_view)

df.dtypes

date              datetime64[ns]
price                    float64
bedrooms                 float64
bathrooms                float64
sqft_living                int64
sqft_lot                   int64
floors                   float64
waterfront                  bool
view                    category
condition               category
sqft_above                 int64
sqft_basement              int64
yr_built                   int64
yr_renovated               int64
street                  category
city                    category
statezip                category
price_per_sqft           float64
mes                        int32
dtype: object

In [91]:
# Booleana: 2 estados que representan sí/no
df['waterfront'] = df['waterfront'].astype(bool)

# Nominal: categorías sin orden -> category simple
df['city'] = df['city'].astype('category')

# Ordinal: categorías CON orden -> category con ordered=True
cat_condition = pd.CategoricalDtype(categories=[1,2,3,4,5], ordered=True)
df['condition'] = df['condition'].astype(cat_condition)

###Analsis Inicial:
- Nominales: `street`, `city`, `statezip`
- Ordinales: `condition` , `view` , `floors`
- Booleanas: `waterfront`
- Numéricas(no nominal / ordinal / booleana):`price`, `sqft_living`, `sqft_lot`, `sqft_above`, `sqft_basement`, `price_per_sqft`,`bedrooms`, `bathrooms`, `yr_built`, `yr_renovated`,`yr_renovated`, `date`

In [92]:
# Filas donde price o sqft_living son 0 o negativos
filas_invalidas = df[(df['price'] <= 0) | (df['sqft_living'] <= 0)]
print("Filas inválidas:", len(filas_invalidas))
df = df[(df['price'] > 0) & (df['sqft_living'] > 0)].reset_index(drop=True)

Filas inválidas: 49

## Paso 3 · Feature engineering: variables temporales - exponer relaciones que el modelo no ve directamente

In [93]:
df['ratio_bano_habitacion'] = df['bathrooms'] / df['bedrooms'].replace(0, np.nan)
df['ratio_bano_habitacion'] = df['ratio_bano_habitacion'].fillna(0)

df['tiene_sotano'] = df['sqft_basement'] > 0
df['ratio_living_lot'] = df['sqft_living'] / df['sqft_lot']
df['ratio_above_living'] = df['sqft_above'] / df['sqft_living']

df['precio_prom_ciudad'] = df.groupby('city', observed=True)['price'].transform('mean')
df['habitaciones_totales'] = df['bedrooms'] + df['bathrooms']

df['log_price'] = np.log1p(df['price'])
df['log_sqft_living'] = np.log1p(df['sqft_living'])

df.filter(regex='ratio_|sotano|prom_ciudad|log_|habitaciones_totales').head()

,ratio_bano_habitacion,tiene_sotano,ratio_living_lot,ratio_above_living,precio_prom_ciudad,habitaciones_totales,log_price,log_sqft_living
0,0.500000,False,0.169363,1.000000,420392.364065,4.50,12.653962,7.201171
1,0.500000,True,0.403315,0.923288,584294.898161,7.50,14.684291,8.202756
2,0.666667,False,0.161547,1.000000,441880.990598,5.00,12.742569,7.565793
3,0.750000,True,0.249066,0.500000,862255.051993,5.25,12.948012,7.601402
4,0.625000,True,0.184762,0.587629,667649.534766,6.50,13.217675,7.570959

## 4. EDA: Revisamos distribución del precio, outliers, relaciones con variables numéricas y con ubicación.